export const social = {
  linkedin: 'https://www.linkedin.com/in/gauravcodes',
  twitter: 'https://twitter.com/gauravcodes',
  email: 'mailto:gthakur581@gmail.com',
  facebook: 'https://www.facebook.com/gauravcodes',
  github: 'https://github.com/thegauravthakur',
  playstore: 'https://play.google.com/store/apps/dev?id=4779143093480615617',
  leetcode: 'https://leetcode.com/thegauravthakur',
  stopstalk: 'https://www.stopstalk.com/user/profile/gaurav_thakur',
  codechef: 'https://www.codechef.com/users/gaurav__thakur',
  codeforces: 'https://codeforces.com/profile/gaurav_thakur',
  spoj: 'https://www.spoj.com/users/gaurav__thakur',
  atcoder: 'https://atcoder.jp/users/gauravthakur',
  hackerearth: 'https://www.hackerearth.com/@gaurav_thakur',
  hackerrank: 'https://www.hackerrank.com/gauravcodes',
  uva: 'https://uhunt.onlinejudge.org/id/1065439',
  timus: 'https://acm.timus.ru/author.aspx?id=295314',
  quora: 'https://www.quora.com/profile/Gaurav-Thakur-219',
  blog: 'https://blog.gauravthakur.in',
  medium: 'https://medium.com/@gauravcodes',
  hashnode: 'https://hashnode.com/@gauravthakur',
}
